public func memoizedCurry<A:Hashable, B>(function: (A) -> B) -> A -> B {
    return memoize({ (`a`: A) -> B in function(`a`) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C>(function: (A, B) -> C) -> A -> B -> C {
    return memoize({ (`a`: A) -> B -> C in memoize({ (`b`: B) -> C in function(`a`, `b`) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D>(function: (A, B, C) -> D) -> A -> B -> C -> D {
    return memoize({ (`a`: A) -> B -> C -> D in memoize({ (`b`: B) -> C -> D in memoize({ (`c`: C) -> D in function(`a`, `b`, `c`) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E>(function: (A, B, C, D) -> E) -> A -> B -> C -> D -> E {
    return memoize({ (`a`: A) -> B -> C -> D -> E in memoize({ (`b`: B) -> C -> D -> E in memoize({ (`c`: C) -> D -> E in memoize({ (`d`: D) -> E in function(`a`, `b`, `c`, `d`) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F>(function: (A, B, C, D, E) -> F) -> A -> B -> C -> D -> E -> F {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F in memoize({ (`b`: B) -> C -> D -> E -> F in memoize({ (`c`: C) -> D -> E -> F in memoize({ (`d`: D) -> E -> F in memoize({ (`e`: E) -> F in function(`a`, `b`, `c`, `d`, `e`) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G>(function: (A, B, C, D, E, F) -> G) -> A -> B -> C -> D -> E -> F -> G {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G in memoize({ (`b`: B) -> C -> D -> E -> F -> G in memoize({ (`c`: C) -> D -> E -> F -> G in memoize({ (`d`: D) -> E -> F -> G in memoize({ (`e`: E) -> F -> G in memoize({ (`f`: F) -> G in function(`a`, `b`, `c`, `d`, `e`, `f`) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H>(function: (A, B, C, D, E, F, G) -> H) -> A -> B -> C -> D -> E -> F -> G -> H {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H in memoize({ (`c`: C) -> D -> E -> F -> G -> H in memoize({ (`d`: D) -> E -> F -> G -> H in memoize({ (`e`: E) -> F -> G -> H in memoize({ (`f`: F) -> G -> H in memoize({ (`g`: G) -> H in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I>(function: (A, B, C, D, E, F, G, H) -> I) -> A -> B -> C -> D -> E -> F -> G -> H -> I {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I in memoize({ (`d`: D) -> E -> F -> G -> H -> I in memoize({ (`e`: E) -> F -> G -> H -> I in memoize({ (`f`: F) -> G -> H -> I in memoize({ (`g`: G) -> H -> I in memoize({ (`h`: H) -> I in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J>(function: (A, B, C, D, E, F, G, H, I) -> J) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J in memoize({ (`e`: E) -> F -> G -> H -> I -> J in memoize({ (`f`: F) -> G -> H -> I -> J in memoize({ (`g`: G) -> H -> I -> J in memoize({ (`h`: H) -> I -> J in memoize({ (`i`: I) -> J in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K>(function: (A, B, C, D, E, F, G, H, I, J) -> K) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K in memoize({ (`f`: F) -> G -> H -> I -> J -> K in memoize({ (`g`: G) -> H -> I -> J -> K in memoize({ (`h`: H) -> I -> J -> K in memoize({ (`i`: I) -> J -> K in memoize({ (`j`: J) -> K in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L>(function: (A, B, C, D, E, F, G, H, I, J, K) -> L) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L in memoize({ (`g`: G) -> H -> I -> J -> K -> L in memoize({ (`h`: H) -> I -> J -> K -> L in memoize({ (`i`: I) -> J -> K -> L in memoize({ (`j`: J) -> K -> L in memoize({ (`k`: K) -> L in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M>(function: (A, B, C, D, E, F, G, H, I, J, K, L) -> M) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M in memoize({ (`h`: H) -> I -> J -> K -> L -> M in memoize({ (`i`: I) -> J -> K -> L -> M in memoize({ (`j`: J) -> K -> L -> M in memoize({ (`k`: K) -> L -> M in memoize({ (`l`: L) -> M in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M) -> N) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N in memoize({ (`i`: I) -> J -> K -> L -> M -> N in memoize({ (`j`: J) -> K -> L -> M -> N in memoize({ (`k`: K) -> L -> M -> N in memoize({ (`l`: L) -> M -> N in memoize({ (`m`: M) -> N in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`) }) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N:Hashable, O>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N -> O in memoize({ (`i`: I) -> J -> K -> L -> M -> N -> O in memoize({ (`j`: J) -> K -> L -> M -> N -> O in memoize({ (`k`: K) -> L -> M -> N -> O in memoize({ (`l`: L) -> M -> N -> O in memoize({ (`m`: M) -> N -> O in memoize({ (`n`: N) -> O in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`) }) }) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N:Hashable, O:Hashable, P>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P in memoize({ (`i`: I) -> J -> K -> L -> M -> N -> O -> P in memoize({ (`j`: J) -> K -> L -> M -> N -> O -> P in memoize({ (`k`: K) -> L -> M -> N -> O -> P in memoize({ (`l`: L) -> M -> N -> O -> P in memoize({ (`m`: M) -> N -> O -> P in memoize({ (`n`: N) -> O -> P in memoize({ (`o`: O) -> P in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N:Hashable, O:Hashable, P:Hashable, Q>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`j`: J) -> K -> L -> M -> N -> O -> P -> Q in memoize({ (`k`: K) -> L -> M -> N -> O -> P -> Q in memoize({ (`l`: L) -> M -> N -> O -> P -> Q in memoize({ (`m`: M) -> N -> O -> P -> Q in memoize({ (`n`: N) -> O -> P -> Q in memoize({ (`o`: O) -> P -> Q in memoize({ (`p`: P) -> Q in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N:Hashable, O:Hashable, P:Hashable, Q:Hashable, R>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`j`: J) -> K -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`k`: K) -> L -> M -> N -> O -> P -> Q -> R in memoize({ (`l`: L) -> M -> N -> O -> P -> Q -> R in memoize({ (`m`: M) -> N -> O -> P -> Q -> R in memoize({ (`n`: N) -> O -> P -> Q -> R in memoize({ (`o`: O) -> P -> Q -> R in memoize({ (`p`: P) -> Q -> R in memoize({ (`q`: Q) -> R in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N:Hashable, O:Hashable, P:Hashable, Q:Hashable, R:Hashable, S>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`j`: J) -> K -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`k`: K) -> L -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`l`: L) -> M -> N -> O -> P -> Q -> R -> S in memoize({ (`m`: M) -> N -> O -> P -> Q -> R -> S in memoize({ (`n`: N) -> O -> P -> Q -> R -> S in memoize({ (`o`: O) -> P -> Q -> R -> S in memoize({ (`p`: P) -> Q -> R -> S in memoize({ (`q`: Q) -> R -> S in memoize({ (`r`: R) -> S in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N:Hashable, O:Hashable, P:Hashable, Q:Hashable, R:Hashable, S:Hashable, T>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`j`: J) -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`k`: K) -> L -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`l`: L) -> M -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`m`: M) -> N -> O -> P -> Q -> R -> S -> T in memoize({ (`n`: N) -> O -> P -> Q -> R -> S -> T in memoize({ (`o`: O) -> P -> Q -> R -> S -> T in memoize({ (`p`: P) -> Q -> R -> S -> T in memoize({ (`q`: Q) -> R -> S -> T in memoize({ (`r`: R) -> S -> T in memoize({ (`s`: S) -> T in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`, `s`) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
}

public func memoizedCurry<A:Hashable, B:Hashable, C:Hashable, D:Hashable, E:Hashable, F:Hashable, G:Hashable, H:Hashable, I:Hashable, J:Hashable, K:Hashable, L:Hashable, M:Hashable, N:Hashable, O:Hashable, P:Hashable, Q:Hashable, R:Hashable, S:Hashable, T:Hashable, U>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U {
    return memoize({ (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`j`: J) -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`k`: K) -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`l`: L) -> M -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`m`: M) -> N -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`n`: N) -> O -> P -> Q -> R -> S -> T -> U in memoize({ (`o`: O) -> P -> Q -> R -> S -> T -> U in memoize({ (`p`: P) -> Q -> R -> S -> T -> U in memoize({ (`q`: Q) -> R -> S -> T -> U in memoize({ (`r`: R) -> S -> T -> U in memoize({ (`s`: S) -> T -> U in memoize({ (`t`: T) -> U in function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`, `s`, `t`) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) })
}
